# Generated by Django 4.0 on 2022-03-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='createde',
            new_name='created',
        ),
    ]
